package Telas;

import PGSQL.DataBaseConnection;
import static java.awt.Frame.MAXIMIZED_BOTH;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author GilbertoNeto
 */
public class IntermediateLoading extends javax.swing.JFrame {
    
    DataBaseConnection conecta = new DataBaseConnection();

    /**
     * Creates new form Greetings
     */
    public IntermediateLoading() {
        initComponents();
        conecta.conexao();
        setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Koalareads");
        setMinimumSize(new java.awt.Dimension(1920, 1080));
        getContentPane().setLayout(null);

        jProgressBar1.setBackground(new java.awt.Color(51, 51, 51));
        getContentPane().add(jProgressBar1);
        jProgressBar1.setBounds(705, 625, 510, 20);

        jLabel5.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 15)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("99");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(575, 650, 770, 20);

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Logos/Logo-VIII.png"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(1535, 910, 380, 80);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Loading II(GIF).gif"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(575, 250, 770, 360);

        jLabel2.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Inicializando");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(575, 585, 770, 27);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Gradient Background.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1920, 1080);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        IntermediateLoading loading = new IntermediateLoading();
        loading.setVisible(true);
        try {
            for (int i = 0; i <= 100; i += 3){
                Thread.sleep(200);
                loading.jProgressBar1.setValue(i);
                loading.jLabel5.setText(Integer.toString(i) + "%");
            }
            loading.dispose();
            
            Greetings obj = new Greetings();
            obj.setVisible(true);
        } catch (InterruptedException e){
            JOptionPane.showConfirmDialog(null, "Erro!");
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JProgressBar jProgressBar1;
    // End of variables declaration//GEN-END:variables
}
